First Commit
priettt/FitTracker pull request #1
Opened 2018-09-18 16:55 UTC by priettt

2018-09-18 17:54 UTC, capraber commented on FitTracker/app/src/main/java/com/pps/globant/fittracker/mvp/view/ActivityView.java
> +//Deprecated
Please remove this comments lines

2018-09-18 17:54 UTC, capraber commented on FitTracker/app/src/main/java/com/pps/globant/fittracker/mvp/presenter/LoginPresenter.java
> +public class LoginPresenter {
Please instantiate this presenter with s simple activity with a place holder text

2018-09-18 19:42 UTC, vsmartinez requested changes
Add gradle/ folder to .gitIgnore

Rule: Do not upload Generated files.

2018-09-18 19:52 UTC, nacho-globant commented on FitTracker/app/src/main/java/com/pps/globant/fittracker/MainActivity.java
> +    LoginPresenter presenter;
Mark as final

2018-09-18 19:52 UTC, nacho-globant commented on FitTracker/app/src/main/java/com/pps/globant/fittracker/MainActivity.java
> +        if (presenter == null) {
you dont need this condition in this place

2018-09-18 19:54 UTC, nacho-globant commented on FitTracker/app/src/main/res/layout/activity_main.xml
> +        android:textSize="40sp"
create an item into dimens.xml for use that value

2018-09-18 19:55 UTC, nacho-globant reviewed
some comments

2018-09-20 14:28 UTC, capraber commented
+1

2018-09-20 15:57 UTC, nacho-globant commented
+1

2018-09-20 15:58 UTC, merged