Login ig saving data in db + fix bugs
priettt/FitTracker pull request #13
Opened 2018-10-22 15:36 UTC by ferdefiore

+Use the db to save IG login information
+Bugs fix:
-Blocking writing in birthday field
-The app was crashing when the email and birthday want to update in the db and at the same time, because was async, another method was triying to send an email to the same user that has been updating.
-Delete a tost from the method SendMail that crash the app because it was triying to show a toast in a view that it has been destroyed.

2018-10-23 18:44 UTC, SartiMau requested changes

2018-10-23 18:44 UTC, SartiMau commented on app/src/main/java/com/pps/globant/fittracker/mvp/presenter/InstagramLoginPresenter.java
> +        String names[] = event.name.split(" ",2);
Put this in a constant please

2018-10-23 18:44 UTC, SartiMau commented on app/src/main/java/com/pps/globant/fittracker/mvp/presenter/InstagramLoginPresenter.java
> +        String id = String.format("IG%s", event.id);
same

2018-10-23 18:44 UTC, SartiMau commented on app/src/main/java/com/pps/globant/fittracker/mvp/presenter/InstagramLoginPresenter.java
> +        bus.post(new IgUserDataRecoveredEvent(User.getUser(names[0], names[1], null, null, id)));
same

2018-10-29 18:56 UTC, ferdefiore commented on app/src/main/java/com/pps/globant/fittracker/mvp/presenter/InstagramLoginPresenter.java
> +        String id = String.format("IG%s", event.id);
done

2018-10-29 18:56 UTC, ferdefiore commented on app/src/main/java/com/pps/globant/fittracker/mvp/presenter/InstagramLoginPresenter.java
> +        String names[] = event.name.split(" ",2);
done

2018-10-30 22:12 UTC, SartiMau approved these changes

2018-10-31 12:04 UTC, capraber approved these changes

2018-10-31 12:04 UTC, merged