Improved sign in screen. Added google to database.
priettt/FitTracker pull request #14
Opened 2018-10-22 18:18 UTC by priettt

2018-10-23 17:21 UTC, capraber approved these changes

2018-10-23 18:30 UTC, SartiMau requested changes

2018-10-23 18:30 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@android:color/white</item>
Make a style that inherits from ThemeOverlay.AppCompat.Dark and have the android:textColor item only. Then make that the all this styles that use that item inherits from this new style.

2018-10-24 15:09 UTC, SartiMau approved these changes

2018-10-24 15:12 UTC, merged